# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-17 01:03
from __future__ import unicode_literals

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MtM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='OtM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='OtO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=1)),
                ('description', models.TextField(default='description belongs here')),
                ('email', models.EmailField(blank=True, default='nobody@nowhere.com', max_length=70)),
                ('money', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=9)),
                ('start_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=False)),
                ('name', models.CharField(default='something', max_length=20)),
                ('url', models.TextField(default='http://localhost:8000/', validators=[django.core.validators.URLValidator()])),
            ],
        ),
        migrations.AddField(
            model_name='oto',
            name='ref',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mysql.Reference'),
        ),
        migrations.AddField(
            model_name='otm',
            name='ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysql.Reference'),
        ),
        migrations.AddField(
            model_name='mtm',
            name='ref',
            field=models.ManyToManyField(to='mysql.Reference'),
        ),
    ]
